name: cripto_qr_googlemarine
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  clock: ^1.1.1
  collection: ^1.17.2
  crypto: ^3.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  lottie: ^2.6.0
  meta: ^1.9.1
  provider: ^6.0.5
  rxdart: ^0.26.0
  uuid: ^4.0.0
  web_socket_channel: ^2.4.0
  url_launcher: ^6.1.14
  jwt_decoder: ^2.0.1
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  cross_file: ^0.3.3+5
  permission_handler: ^10.4.3
  firebase_core: ^2.15.1
  firebase_crashlytics: ^3.3.5
  firebase_analytics: ^10.4.5
  firebase_performance: ^0.9.2+5
  flutter_image_compress: ^2.0.4
  firebase_storage: ^11.2.6
  firebase_remote_config: ^4.2.5
  cupertino_icons: ^1.0.2
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  encrypt: ^5.0.1
  image_gallery_saver: '^2.0.3'
  cloud_firestore: ^4.9.1
  esc_pos_printer: ^4.1.0
  esc_pos_bluetooth: ^0.4.1
  esc_pos_utils: ^1.1.0
  image: ^3.0.12
  widgets_to_image: ^0.0.2
  blue_thermal_printer: ^1.2.3
  shared_preferences: ^2.2.2
  sqlite3: ^2.1.0
  sqflite: ^2.3.0
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/imgs/illustrations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Semibold.otf
          weight: 600
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
