name: dockcheck
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  clock: ^1.1.1
  collection: ^1.17.2
  crypto: ^3.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  provider: ^6.0.5
  rxdart: ^0.26.0
  uuid: ^4.0.0
  web_socket_channel: ^2.4.0
  url_launcher: ^6.1.14
  jwt_decoder: ^2.0.1
  package_info_plus: ^4.1.0
  path_provider: ^2.1.1
  permission_handler: ^10.4.3
  cupertino_icons: ^1.0.2
  encrypt: ^5.0.1
  image_gallery_saver: '^2.0.3'
  image: ^3.0.12
  widgets_to_image: ^0.0.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  flutter_blue_plus: ^1.30.3
  http: ^1.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  bloc_test: ^9.1.4
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/imgs/
    - assets/imgs/illustrations/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Semibold.otf
          weight: 600
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
